name: Create Windows Server VM + Tailscale + Show Access + Keep Alive

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  create-vm:
    runs-on: ubuntu-latest
    timeout-minutes: 370 # maxim 6 ore plus buffer

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/PROJECT_NUMBER/locations/global/workloadIdentityPools/POOL_NAME/providers/PROVIDER_NAME'
          service_account: 'your-service-account@your-project.iam.gserviceaccount.com'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v3
        with:
          version: 'latest'

      - name: Set zone and machine type
        run: |
          gcloud config set project your-google-cloud-project-id
          gcloud config set compute/zone us-central1-a
          echo "custom-8-32768" > machine_type.txt

      - name: Create 600GB SSD disk
        run: |
          gcloud compute disks create windows-server-disk --size=600GB --type=pd-ssd --zone=us-central1-a

      - name: Create Windows Server 2025 VM
        run: |
          MACHINE_TYPE=$(cat machine_type.txt)
          gcloud compute instances create windows-server-vm \
            --zone=us-central1-a \
            --machine-type=$MACHINE_TYPE \
            --disk=name=windows-server-disk,boot=yes,auto-delete=yes \
            --image-family=windows-2025 \
            --image-project=windows-cloud \
            --metadata=windows-startup-script-cmd="powershell -Command \"Write-Host 'VM pornita'\"" \
            --no-address

      - name: Install Tailscale and reset RDPUser password
        id: setup_vm
        run: |
          PASS=$(openssl rand -base64 12)
          gcloud compute ssh windows-server-vm --zone=us-central1-a --command="powershell -Command `
            Invoke-WebRequest https://pkgs.tailscale.com/stable/tailscale-setup-1.82.0-amd64.msi -OutFile C:\\tailscale.msi; `
            Start-Process msiexec.exe -ArgumentList '/i', 'C:\\tailscale.msi', '/quiet', '/norestart' -Wait; `
            Remove-Item C:\\tailscale.msi; `
            & 'C:\\Program Files\\Tailscale\\tailscale.exe' up --authkey=${{ secrets.TAILSCALE_AUTH_KEY }} --hostname=gh-vm-$Env:GITHUB_RUN_ID; `
            net user RDPUser $env:PASS /add /active:yes; `
            net localgroup administrators RDPUser /add; `
            Set-Content -Path C:\\pass.txt -Value $env:PASS" -- -o SendEnv=PASS
          echo "::set-output name=password::$PASS"

      - name: Show Tailscale IP and RDP credentials
        run: |
          IP=$(gcloud compute ssh windows-server-vm --zone=us-central1-a --command="& 'C:\\Program Files\\Tailscale\\tailscale.exe' ip -4 | Out-String")
          echo "IP Tailscale: $IP"
          echo "User: RDPUser"
          echo "Password: ${{ steps.setup_vm.outputs.password }}"

      - name: Keep VM alive for 6 hours
        run: sleep 21600
        
